name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main # Replace with your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install and configure dependencies
        run: |
          npm ci
          npm i -g @cloudflare/wrangler

      - name: Configure Wrangler
        run: |
          echo "CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}" > ~/.wrangler/config/default.toml
          echo "CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}" >> ~/.wrangler/config/default.toml

      - name: Deploy to Cloudflare Workers
        run: wrangler publish
